name: isoformx
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - pysam>=0.21
  - biopython>=1.81
  - click>=8.1
  - tqdm>=4.65
  - matplotlib>=3.7
  - seaborn>=0.12
  - pytest>=7.4
  - pytest-cov>=4.1
  - black>=23.0
  - flake8>=6.0
  - mypy>=1.5
  - pip
  - pip:
    - gffutils>=0.12
    - pyfaidx>=0.7
